# Generated by Django 4.1.7 on 2023-03-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images/")),
                ("image_caption", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("house_number", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=255)),
                ("town_city", models.CharField(max_length=50)),
                ("province_state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("date_of_death", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("envelope", "Envelope"),
                            ("postcard", "Postcard"),
                            ("letter form", "Letter Form"),
                            ("newsprint", "Newsprint"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postcard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("item_number", models.IntegerField()),
                ("postmark_1_date", models.DateField()),
                ("postmark_1_location", models.CharField(max_length=50)),
                ("postmark_2_date", models.DateField()),
                ("postmark_2_location", models.CharField(max_length=50)),
                ("return_to_sender", models.BooleanField()),
                ("date_returned", models.DateField(blank=True, null=True)),
                (
                    "reason_for_return",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("regime_censor", models.BooleanField()),
                ("date_of_correspondence", models.DateField()),
                ("letter_enclosed", models.BooleanField()),
                ("translated", models.BooleanField()),
                ("other", models.CharField(max_length=50)),
                ("notes", models.TextField(max_length=255)),
                (
                    "addressee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addressee_name",
                        to="postcards.person",
                        verbose_name="addressee's name",
                    ),
                ),
                (
                    "image",
                    models.ManyToManyField(to="postcards.image", verbose_name="image"),
                ),
                (
                    "sender_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_name",
                        to="postcards.person",
                        verbose_name="sender's name",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="postcards.tag", verbose_name="tags"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postcards.type",
                        verbose_name="type of artifact",
                    ),
                ),
            ],
        ),
    ]
