# Generated by Django 4.1.7 on 2023-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="province_state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="State/Province"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="town_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Town/City"
            ),
        ),
    ]
