# Generated by Django 4.1.7 on 2023-03-23 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcard",
            old_name="id",
            new_name="postcard_id",
        ),
    ]
