# Generated by Django 4.1.7 on 2023-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0003_location_created_at_location_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postmark",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="postcard",
            name="postmark_1_date",
        ),
        migrations.RemoveField(
            model_name="postcard",
            name="postmark_1_location",
        ),
        migrations.RemoveField(
            model_name="postcard",
            name="postmark_2_date",
        ),
        migrations.RemoveField(
            model_name="postcard",
            name="postmark_2_location",
        ),
        migrations.AddField(
            model_name="postcard",
            name="postmark",
            field=models.ManyToManyField(
                to="postcards.postmark", verbose_name="postmark"
            ),
        ),
    ]
