# Generated by Django 4.1.7 on 2023-03-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0004_postmark_remove_postcard_postmark_1_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="id",
            new_name="image_id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="id",
            new_name="location_id",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="id",
            new_name="person_id",
        ),
        migrations.RenameField(
            model_name="postmark",
            old_name="id",
            new_name="postmark_id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="id",
            new_name="tag_id",
        ),
        migrations.AddField(
            model_name="postmark",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postmark",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postmark",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="postcards.location"
            ),
        ),
    ]
