# Generated by Django 4.1.7 on 2023-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0005_alter_person_house_number_alter_person_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
