# Generated by Django 4.1.7 on 2023-03-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("postcards", "0005_rename_id_image_image_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcard",
            name="item_number",
        ),
        migrations.AddField(
            model_name="postcard",
            name="check_sensative_content",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you think this postcard contains sensitive imagery or events.",
            ),
        ),
        migrations.AddField(
            model_name="postcard",
            name="item_id",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="postcard",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="date_returned",
            field=models.DateField(
                blank=True,
                help_text="Insert the date as YYYY-MM-DD or use the date picker. Leave blank if unknown or N/A.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="notes",
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="postmark",
            field=models.ManyToManyField(
                related_name="postmark",
                to="postcards.postmark",
                verbose_name="postmark",
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="reason_for_return",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="regime_censor",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="return_to_sender",
            field=models.BooleanField(
                help_text="Check the box if the postcard was returned to sender."
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="translated",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("partial", "Partial")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="type",
            field=models.CharField(
                choices=[
                    ("envelope", "Envelope"),
                    ("postcard", "Postcard"),
                    ("letter form", "Letter Form"),
                    ("newsprint", "Newsprint"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
