# Generated by Django 4.1.7 on 2023-03-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0006_remove_postcard_item_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Type",
        ),
        migrations.RemoveField(
            model_name="postcard",
            name="title",
        ),
        migrations.AlterField(
            model_name="postcard",
            name="date_returned",
            field=models.DateField(
                blank=True,
                help_text="Insert the date as YYYY-MM-DD or use the date picker. Leave blank if unknown.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="postmark",
            field=models.ManyToManyField(
                to="postcards.postmark", verbose_name="postmark"
            ),
        ),
    ]
