# Generated by Django 4.1.7 on 2023-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0006_alter_person_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["town_city"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name"]},
        ),
        migrations.AddField(
            model_name="person",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
