# Generated by Django 4.1.7 on 2023-09-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0007_alter_location_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=55)),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 639 code for this language (2 or 3 letters)",
                        max_length=3,
                        verbose_name="ISO Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["language"],
            },
        ),
        migrations.RemoveField(
            model_name="object",
            name="transcription",
        ),
        migrations.AddField(
            model_name="object",
            name="regime_censor_location",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the location of the censor. If the location does not exist, click the plus and add the new location.",
                to="postcards.location",
            ),
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "transcription_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True, help_text="Transcription of the document", null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select the language of this transcription",
                        to="postcards.language",
                    ),
                ),
                (
                    "postal_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link a document to the transcription.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postcards.object",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                fields=("language", "display_name"), name="unique_language_display_name"
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="text",
            field=models.ForeignKey(
                blank=True,
                help_text="Add the document's transcription and language.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.transcription",
                verbose_name="Transcription",
            ),
        ),
    ]
