# Generated by Django 4.1.7 on 2023-03-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0007_delete_type_remove_postcard_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="other",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red cross", "Red Cross"),
                    ("uberroller", "Uberroller"),
                    ("pow", "POW"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
