# Generated by Django 4.1.7 on 2023-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0008_alter_postcard_other"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.RemoveField(
            model_name="postmark",
            name="date",
        ),
        migrations.AlterField(
            model_name="postcard",
            name="item_id",
            field=models.CharField(
                default="N/A", max_length=255, verbose_name="Item ID"
            ),
        ),
    ]
