# Generated by Django 4.1.7 on 2023-09-26 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0008_language_remove_object_transcription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="text",
        ),
    ]
