# Generated by Django 4.1.7 on 2023-10-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0009_remove_object_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="postcard",
        ),
        migrations.RemoveField(
            model_name="object",
            name="translation",
        ),
        migrations.AddField(
            model_name="object",
            name="public_notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are visible to the public.",
                null=True,
                verbose_name="Public notes",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Related images refers to photographs or ancillary sources related to a postal item.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="check_sensative_content",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you think this postcard contains sensitive imagery or events.",
                verbose_name="Material contains sensitive content",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="collection_location",
            field=models.ForeignKey(
                help_text="The location in the collection (folder and box).",
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.archive",
                verbose_name="Location in the Collection",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload images of the object(s).",
                null=True,
                upload_to="files/",
                verbose_name="Upload images",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="item_id",
            field=models.CharField(
                default="N/A",
                help_text="Record the file name of the image here.",
                max_length=255,
                verbose_name="Item ID",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are not visible to the public.",
                null=True,
                verbose_name="Internal notes",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="translated",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("partial", "Partial")],
                help_text="Has the material been translated?",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ReasonReturn",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Notes on the reason for return.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select the language of this return.",
                        to="postcards.language",
                    ),
                ),
                (
                    "postal_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link a document to the reason for return.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postcards.object",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
