# Generated by Django 4.1.7 on 2023-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0010_remove_postmark_latitude_remove_postmark_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmark",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Insert the date as YYYY-MM-DD or use the date picker. Leave blank if unknown.",
                null=True,
            ),
        ),
    ]
