# Generated by Django 4.1.7 on 2023-10-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0010_remove_image_postcard_remove_object_translation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AncillarySources",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("service record", "Service Record"),
                            ("military record", "Military Record"),
                            ("newspaper", "Newspaper"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload images of the object(s).",
                        null=True,
                        upload_to="files/",
                        verbose_name="Upload images",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to="postcards.person",
                        verbose_name="person",
                    ),
                ),
            ],
        ),
    ]
