# Generated by Django 4.1.7 on 2023-03-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0012_alter_location_city_alter_location_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="city",
            new_name="town_city",
        ),
        migrations.RemoveField(
            model_name="person",
            name="country",
        ),
        migrations.RemoveField(
            model_name="person",
            name="province_state",
        ),
        migrations.RemoveField(
            model_name="person",
            name="town_city",
        ),
        migrations.AddField(
            model_name="location",
            name="province_state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.location",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="Image ID"
            ),
        ),
    ]
