# Generated by Django 4.1.7 on 2023-10-19 20:03

import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("postcards", "0012_rename_ancillarysources_ancillarysource"),
    ]

    operations = [
        migrations.AddField(
            model_name="ancillarysource",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the document.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="ancillarysource",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are not visible to the public.",
                null=True,
                verbose_name="Internal notes",
            ),
        ),
        migrations.AddField(
            model_name="ancillarysource",
            name="public_notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are visible to the public.",
                null=True,
                verbose_name="Public notes",
            ),
        ),
        migrations.AddField(
            model_name="ancillarysource",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="ancillarysource",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("service record", "Service Record"),
                    ("military record", "Military Record"),
                    ("newspaper", "Newspaper"),
                    ("report", "Report"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
