# Generated by Django 4.1.7 on 2023-03-24 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "postcards",
            "0013_rename_city_location_town_city_remove_person_country_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_id",
                    models.CharField(
                        default="N/A", max_length=255, verbose_name="Item ID"
                    ),
                ),
                (
                    "return_to_sender",
                    models.BooleanField(
                        help_text="Check the box if the postcard was returned to sender."
                    ),
                ),
                (
                    "date_returned",
                    models.DateField(
                        blank=True,
                        help_text="Insert the date as YYYY-MM-DD or use the date picker. Leave blank if unknown.",
                        null=True,
                    ),
                ),
                (
                    "reason_for_return",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "regime_censor",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("envelope", "Envelope"),
                            ("postcard", "Postcard"),
                            ("letter form", "Letter Form"),
                            ("newsprint", "Newsprint"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_of_correspondence", models.DateField()),
                ("letter_enclosed", models.BooleanField()),
                (
                    "translated",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("partial", "Partial")],
                        max_length=50,
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red cross", "Red Cross"),
                            ("uberroller", "Uberroller"),
                            ("pow", "POW"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(max_length=600)),
                (
                    "check_sensative_content",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if you think this postcard contains sensitive imagery or events.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "addressee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addressee_name",
                        to="postcards.person",
                        verbose_name="addressee's name",
                    ),
                ),
                (
                    "image",
                    models.ManyToManyField(to="postcards.image", verbose_name="image"),
                ),
                (
                    "postmark",
                    models.ManyToManyField(
                        to="postcards.postmark", verbose_name="postmark"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_name",
                        to="postcards.person",
                        verbose_name="sender's name",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="postcards.tag", verbose_name="tags"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Postcard",
        ),
    ]
