# Generated by Django 4.1.7 on 2023-10-19 22:33

import django.db.models.deletion
import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        (
            "postcards",
            "0013_ancillarysource_description_ancillarysource_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimarySource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("service record", "Service Record"),
                            ("military record", "Military Record"),
                            ("newspaper", "Newspaper"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload images of the object(s).",
                        null=True,
                        upload_to="files/",
                        verbose_name="Upload images",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describe the document.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True,
                        help_text="Transcribe the document.",
                        null=True,
                        verbose_name="Transcription",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="These notes are not visible to the public.",
                        null=True,
                        verbose_name="Internal notes",
                    ),
                ),
                (
                    "public_notes",
                    models.TextField(
                        blank=True,
                        help_text="These notes are visible to the public.",
                        null=True,
                        verbose_name="Public notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to="postcards.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "tags",
                    taggit_selectize.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Keywords",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AncillarySource",
        ),
    ]
