# Generated by Django 4.1.7 on 2023-03-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0014_object_delete_postcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="postcard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="postcards.object",
            ),
        ),
    ]
