# Generated by Django 4.1.7 on 2023-10-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0014_primarysource_delete_ancillarysource"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarysource",
            name="related_postal_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="If necessary, link to postal items related to this document. To select more than one, hold down the control key and click on the items you want to select.",
                to="postcards.object",
                verbose_name="Related postal items",
            ),
        ),
        migrations.RemoveField(
            model_name="primarysource",
            name="person",
        ),
        migrations.AddField(
            model_name="primarysource",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the person this document is about. If the person does not exist, click the plus and add the new person.",
                null=True,
                related_name="person",
                to="postcards.person",
                verbose_name="person",
            ),
        ),
    ]
