# Generated by Django 4.1.7 on 2023-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0016_delete_tag_alter_object_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="tags",
        ),
    ]
