# Generated by Django 4.1.7 on 2023-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0016_alter_primarysource_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarysource",
            name="item_id",
            field=models.CharField(
                default="N/A",
                help_text="Record the file name of the image here.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="primarysource",
            name="printer",
            field=models.CharField(
                blank=True,
                help_text="Name of the printer.",
                max_length=255,
                null=True,
                verbose_name="Printer",
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("service record", "Service Record"),
                    ("military record", "Military Record"),
                    ("newspaper", "Newspaper"),
                    ("certificate", "Certificate"),
                    ("typed letter", "Typed Letter"),
                    ("identification card", "Identification Card"),
                    ("book", "Book"),
                    ("loose pages", "Loose Pages"),
                    ("photograph", "Photograph"),
                    ("license", "License"),
                    ("membership card", "Membership Card"),
                    ("letter", "Letter"),
                    ("letter/license", "Letter/License"),
                    ("pay record", "Pay Record"),
                    ("account balance", "Account Balance"),
                    ("papers", "Papers"),
                    ("discharge form", "Discharge Form"),
                    ("pamphlet", "Pamphlet"),
                    ("flyer", "Flyer"),
                    ("program", "Program"),
                    ("typewritten certificate", "Typewritten Certificate"),
                    ("card", "Card"),
                    ("identity card", "Identity Card"),
                    ("booklet", "Booklet"),
                    ("folded card", "Folded Card"),
                    ("voucher", "Voucher"),
                    ("pass", "Pass"),
                    ("report", "Report"),
                    ("stamps", "Stamps"),
                    ("lettersheet", "Lettersheet"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="related_postal_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="If necessary, link to postal items related to this document. Hold down “Control”, or “Command” on a Mac, to select more than one.",
                to="postcards.object",
                verbose_name="Related postal items",
            ),
        ),
    ]
