# Generated by Django 4.1.7 on 2023-10-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "postcards",
            "0018_remove_object_file_image_postcard_alter_image_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primarysource",
            name="file",
        ),
        migrations.AddField(
            model_name="image",
            name="historical_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="postcards.primarysource",
            ),
        ),
    ]
