# Generated by Django 4.1.7 on 2023-06-21 19:39

import django.db.models.deletion
import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("postcards", "0018_object_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="object",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("postcard", "Postcard"),
                    ("letter", "Letter"),
                    ("package", "Package"),
                    ("envelope", "Envelope"),
                ],
                default="envelope",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="object",
            name="transcription",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="translation",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="object",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Keywords",
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="collection_location",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.collection",
                verbose_name="Location in the Collection",
            ),
            preserve_default=False,
        ),
    ]
