# Generated by Django 4.1.7 on 2023-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0019_remove_primarysource_file_image_historical_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="date_of_correspondence",
            field=models.DateField(blank=True, null=True),
        ),
    ]
