# Generated by Django 4.1.7 on 2023-06-21 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0020_alter_object_letter_type_alter_object_notes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="Archive",
        ),
    ]
