# Generated by Django 4.1.7 on 2023-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0022_object_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="type",
        ),
        migrations.AddField(
            model_name="object",
            name="related_images",
            field=models.ManyToManyField(
                blank=True, to="postcards.image", verbose_name="Related images"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("postcard", "Postcard"),
                    ("letter", "Letter"),
                    ("package", "Package"),
                    ("envelope", "Envelope"),
                ],
                max_length=50,
            ),
        ),
    ]
