# Generated by Django 4.1.7 on 2023-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0022_alter_reasonreturn_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reasonreturn",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="transcription",
            managers=[],
        ),
        migrations.AlterField(
            model_name="object",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("postcard", "Postcard"),
                    ("letter", "Letter"),
                    ("package", "Package"),
                    ("envelope", "Envelope"),
                    ("folded card", "Folded Card"),
                    ("envelope printed matter", "Envelope ('printed matter')"),
                    ("letter sheet", "Letter Sheet"),
                    ("giro envelope", "Giro Envelope"),
                ],
                max_length=50,
            ),
        ),
    ]
