# Generated by Django 4.1.7 on 2023-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0023_remove_object_type_object_related_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "collection_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Collection ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
