# Generated by Django 4.1.7 on 2023-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0024_alter_reasonreturn_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="collection_location",
            field=models.CharField(
                help_text="The location in the collection (folder and box).",
                max_length=255,
                verbose_name="collection location",
            ),
        ),
    ]
