# Generated by Django 4.1.7 on 2023-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0024_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="collection",
            field=models.ManyToManyField(
                to="postcards.collection", verbose_name="collection"
            ),
        ),
    ]
