# Generated by Django 4.1.7 on 2023-11-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0025_alter_object_collection_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="addressee_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addressee_name",
                to="postcards.person",
                verbose_name="addressee's name",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="sender_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_name",
                to="postcards.person",
                verbose_name="sender's name",
            ),
        ),
    ]
