# Generated by Django 4.1.7 on 2023-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0026_alter_object_addressee_name_alter_object_sender_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysource",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("service record", "Service Record"),
                    ("military record", "Military Record"),
                    ("newspaper", "Newspaper"),
                    ("certificate", "Certificate"),
                    ("typed letter", "Typed Letter"),
                    ("identification card", "Identification Card"),
                    ("book", "Book"),
                    ("loose pages", "Loose Pages"),
                    ("photograph", "Photograph"),
                    ("license", "License"),
                    ("membership card", "Membership Card"),
                    ("letter", "Letter"),
                    ("letter/license", "Letter/License"),
                    ("pay record", "Pay Record"),
                    ("account balance", "Account Balance"),
                    ("papers", "Papers"),
                    ("discharge form", "Discharge Form"),
                    ("pamphlet", "Pamphlet"),
                    ("flyer", "Flyer"),
                    ("program", "Program"),
                    ("typewritten certificate", "Typewritten Certificate"),
                    ("card", "Card"),
                    ("identity card", "Identity Card"),
                    ("booklet", "Booklet"),
                    ("folded card", "Folded Card"),
                    ("voucher", "Voucher"),
                    ("pass", "Pass"),
                    ("report", "Report"),
                    ("stamps", "Stamps"),
                    ("lettersheet", "Lettersheet"),
                    ("other", "Other"),
                    ('envelope ("printed matter")', 'Envelope ("printed matter")'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="related_postal_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="If necessary, link to postal items related to this document. Hold down “Control”, or “Command” on a Mac, to select more than one.",
                null=True,
                to="postcards.object",
                verbose_name="Related postal items",
            ),
        ),
    ]
