# Generated by Django 4.1.7 on 2023-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0027_alter_primarysource_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysource",
            name="related_postal_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="If necessary, link to postal items related to this document. Hold down “Control”, or “Command” on a Mac, to select more than one.",
                to="postcards.object",
                verbose_name="Related postal items",
            ),
        ),
    ]
