# Generated by Django 4.1.7 on 2023-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0032_alter_object_letter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmark",
            name="ordered_by_arrival",
            field=models.IntegerField(
                blank=True,
                help_text="If there are multiple postmarks, indicate the order by arrival (1, 2, 3, etc.).",
                null=True,
            ),
        ),
    ]
