# Generated by Django 4.1.7 on 2023-11-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "postcards",
            "0034_person_first_name_unknown_person_last_name_unknown_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="associated_with_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.person",
            ),
        ),
    ]
