# Generated by Django 4.1.7 on 2023-11-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0035_organization_associated_with_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="entity_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="entity_type",
            field=models.CharField(
                choices=[("person", "Person"), ("organization", "Organization")],
                default="person",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="associated_with_person",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postcards.person",
            ),
        ),
    ]
