# Generated by Django 4.1.7 on 2023-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0036_person_entity_name_person_entity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="entity_type",
            field=models.CharField(
                choices=[("person", "Person"), ("organization", "Organization")],
                default="person",
                help_text="If this is an organization or some other non-person entity, select the appropriate type.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="This will be auto-generated if left empty.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="This will be auto-generated if left empty.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
