# Generated by Django 4.1.7 on 2023-11-15 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0037_alter_person_entity_type_alter_person_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name"], "verbose_name": "Entities and Person"},
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
