# Generated by Django 4.1.7 on 2023-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0040_alter_person_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="regime_censor_location",
        ),
        migrations.AddField(
            model_name="object",
            name="regime_city",
            field=models.CharField(
                blank=True,
                help_text="Provide the censor's city, if available.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="regime_country",
            field=models.CharField(
                blank=True,
                help_text="Provide the censor's country, if available.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="regime_name",
            field=models.CharField(
                blank=True,
                help_text="This is the text of the stamp used by the censor.",
                max_length=250,
                null=True,
            ),
        ),
    ]
