# Generated by Django 4.1.7 on 2023-12-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0043_remove_transcription_language_transcription_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="language",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Select the language of this transcription",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.language",
            ),
        ),
    ]
