# Generated by Django 4.1.7 on 2023-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0045_alter_object_postmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="postmark",
            field=models.ManyToManyField(
                blank=True, to="postcards.postmark", verbose_name="postmark"
            ),
        ),
    ]
