# Generated by Django 4.1.7 on 2023-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0046_alter_object_postmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="first_name_unclear",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if the first name is unclear.",
                verbose_name="First name unclear",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name_unclear",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if the last name is unclear.",
                verbose_name="Last name unclear",
            ),
        ),
    ]
