# Generated by Django 4.1.7 on 2024-01-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0048_alter_language_iso_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="regime_city",
        ),
        migrations.RemoveField(
            model_name="object",
            name="regime_country",
        ),
        migrations.RemoveField(
            model_name="object",
            name="regime_name",
        ),
        migrations.CreateModel(
            name="Censor",
            fields=[
                ("censor_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "censor_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the censor location.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "censor_notes",
                    models.TextField(
                        blank=True, help_text="Notes on the censor.", null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "censor_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="The location of the censor.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postcards.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="object",
            name="regime_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The location of the censor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.censor",
            ),
        ),
    ]
