# Generated by Django 4.1.7 on 2024-01-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0049_remove_object_regime_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="regime_censor_date",
            field=models.DateField(
                blank=True,
                help_text="Insert the date of the censor as YYYY-MM-DD. Leave blank if unknown.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="regime_censor",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                help_text="Was the postal object censored?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="regime_location",
            field=models.ForeignKey(
                blank=True,
                help_text="If the postal object was censored, select the censor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.censor",
            ),
        ),
    ]
