# Generated by Django 4.1.7 on 2024-01-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "postcards",
            "0050_object_regime_censor_date_alter_object_regime_censor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="historical_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="postcards.primarysource",
            ),
        ),
    ]
