# Generated by Django 4.1.7 on 2024-01-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("postcards", "0052_remove_image_historical_source_primarysource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="reviewed_by_date",
            field=models.DateField(
                blank=True,
                help_text="Insert the date as YYYY-MM-DD or use the date picker.",
                null=True,
                verbose_name="Date last reviewed",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the last user who reviewed this document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
