# Generated by Django 4.2.10 on 2024-03-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "postcards",
            "0056_alter_object_addressee_name_alter_object_sender_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="postal_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Link a document to the transcription.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transcriptions",
                to="postcards.object",
            ),
        ),
    ]
