# Generated by Django 4.2.11 on 2024-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0057_alter_transcription_postal_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarysource",
            name="is_date_known_or_precise",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if the date is unknown or not precise.",
                verbose_name="Is the date unknown or imprecise?",
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the person(s) this document is about. If the person does not exist, click the plus and add the new person.",
                related_name="person",
                to="postcards.person",
                verbose_name="Person",
            ),
        ),
    ]
