# Generated by Django 4.2.11 on 2024-04-24 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("postcards", "0058_primarysource_is_date_known_or_precise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarysource",
            name="cataloger",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the user who cataloged or indexed this document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cataloger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="primarysource",
            name="collection_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The location in the collection (folder and box).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.archive",
            ),
        ),
    ]
