# Generated by Django 4.2.11 on 2024-04-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0060_primarysource_has_document_been_translated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarysource",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.archive",
            ),
        ),
        migrations.AddField(
            model_name="primarysource",
            name="date_cataloged",
            field=models.DateField(
                blank=True,
                help_text="Enter the date this item was cataloged.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="primarysource",
            name="medium",
            field=models.CharField(
                blank=True, help_text="The medium of the document.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="collection_location",
            field=models.CharField(
                blank=True,
                help_text="The location in the collection (folder and box).",
                max_length=255,
                null=True,
                verbose_name="collection location",
            ),
        ),
    ]
