# Generated by Django 4.2.11 on 2024-04-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0062_alter_primarysource_collection_delete_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysource",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postcards.collection",
                verbose_name="collection",
            ),
        ),
    ]
