# Generated by Django 4.2.11 on 2024-04-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0063_alter_primarysource_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysource",
            name="date",
            field=models.CharField(blank=True, null=True),
        ),
    ]
