# Generated by Django 4.2.11 on 2024-04-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0064_alter_primarysource_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="primary_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="postcards.primarysource",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="postcard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="postcards.object",
            ),
        ),
        migrations.AlterField(
            model_name="primarysource",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("service record", "Service Record"),
                    ("military record", "Military Record"),
                    ("newspaper", "Newspaper"),
                    ("certificate", "Certificate"),
                    ("typed letter", "Typed Letter"),
                    ("identification card", "Identification Card"),
                    ("book", "Book"),
                    ("loose pages", "Loose Pages"),
                    ("photograph", "Photograph"),
                    ("license", "License"),
                    ("membership card", "Membership Card"),
                    ("letter", "Letter"),
                    ("letter/license", "Letter/License"),
                    ("pay record", "Pay Record"),
                    ("account balance", "Account Balance"),
                    ("papers", "Papers"),
                    ("discharge form", "Discharge Form"),
                    ("pamphlet", "Pamphlet"),
                    ("flyer", "Flyer"),
                    ("program", "Program"),
                    ("typewritten certificate", "Typewritten Certificate"),
                    ("card", "Card"),
                    ("identity card", "Identity Card"),
                    ("booklet", "Booklet"),
                    ("folded card", "Folded Card"),
                    ("voucher", "Voucher"),
                    ("pass", "Pass"),
                    ("report", "Report"),
                    ("stamps", "Stamps"),
                    ("lettersheet", "Lettersheet"),
                    ("other", "Other"),
                    ('envelope ("printed matter")', 'Envelope ("printed matter")'),
                ],
                max_length=255,
            ),
        ),
    ]
