# Generated by Django 4.2.11 on 2024-04-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0066_alter_image_primary_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="postcard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="postcards.object",
            ),
        ),
    ]
