# Generated by Django 4.2.11 on 2024-04-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0067_alter_image_postcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysource",
            name="item_id",
            field=models.CharField(
                default="N/A",
                help_text="Record the file name of the image here.",
                max_length=255,
            ),
        ),
    ]
