# Generated by Django 4.2.11 on 2024-04-25 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0068_alter_primarysource_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primarysource",
            name="file",
        ),
    ]
