# Generated by Django 4.2.11 on 2024-04-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcards", "0069_remove_primarysource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="postal_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Link a document to the transcription.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcriptions",
                to="postcards.object",
            ),
        ),
    ]
