# Generated by Django 4.1.7 on 2023-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_contributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_volunteer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Student"),
                    (2, "Contributor"),
                    (3, "Volunteer"),
                    (4, "Admin"),
                ],
                default=2,
                null=True,
            ),
        ),
    ]
